chore: update pre-commit

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -5,7 +5,7 @@ fi
 
 if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
 then
-  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR."
+  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
 fi
 
 npm run lint
